#!/usr/bin/env python3
"""Render comment-front-matter LaTeX sources as embedded HTML fragments."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path


SKILL_DIR = Path(__file__).resolve().parent.parent
ASSET_DIR = SKILL_DIR / "assets" / "latex-html"
GENERATED_MARKER = "<!-- Generated by publish-work/render-latex-publications.py. -->"
FONT_NAMES = ("P052-Roman.otf", "P052-Bold.otf", "P052-Italic.otf", "P052-BoldItalic.otf")
FONT_DIRS = (
    Path("/usr/share/fonts/opentype/urw-base35"),
    Path("/usr/share/fonts/truetype/urw-base35"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--site-root", type=Path, required=True)
    parser.add_argument("--css-output", type=Path, required=True)
    parser.add_argument(
        "--metadata-field",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="Front-matter field appended to every generated fragment.",
    )
    return parser.parse_args()


def extract_front_matter(source: str, path: Path) -> tuple[list[str], str]:
    lines = source.splitlines()
    if not lines or lines[0].strip() != "%---":
        raise ValueError(f"{path}: expected comment-prefixed YAML front matter")
    metadata: list[str] = []
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "%---":
            body = "\n".join(lines[index + 1 :]) + "\n"
            return metadata, body
        if not line.startswith("%"):
            raise ValueError(f"{path}:{index + 1}: front matter line must begin with %")
        metadata.append(line[1:] if not line.startswith("% ") else line[2:])
    raise ValueError(f"{path}: unterminated front matter")


def find_font(name: str) -> Path:
    for directory in FONT_DIRS:
        candidate = directory / name
        if candidate.exists():
            return candidate
    raise FileNotFoundError(f"Required P052 font not found: {name}")


def install_shared_assets(css_output: Path) -> None:
    css_output.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(ASSET_DIR / "publication-fragment.css", css_output)
    font_output = css_output.parent / "fonts"
    font_output.mkdir(parents=True, exist_ok=True)
    for name in FONT_NAMES:
        shutil.copy2(find_font(name), font_output / name)


def body_fragment(document: str, path: Path) -> str:
    match = re.search(r"<body[^>]*>(.*)</body>", document, flags=re.DOTALL | re.IGNORECASE)
    if not match:
        raise ValueError(f"{path}: TeX4ht output has no body")
    fragment = match.group(1)
    fragment = re.sub(r"<h3(?=[ >])", "<h2", fragment)
    fragment = re.sub(r"</h3>", "</h2>", fragment)
    fragment = re.sub(r"<h4(?=[ >])", "<h3", fragment)
    fragment = re.sub(r"</h4>", "</h3>", fragment)
    fragment = re.sub(r"<h5(?=[ >])", "<h4", fragment)
    fragment = re.sub(r"</h5>", "</h4>", fragment)
    return fragment.strip()


def render(source: Path, site_root: Path) -> str:
    _, tex_body = extract_front_matter(source.read_text(encoding="utf-8"), source)
    with tempfile.TemporaryDirectory(prefix="publication-html-") as temp_name:
        temp = Path(temp_name)
        staged_source = temp / source.name
        staged_source.write_text(tex_body, encoding="utf-8")
        output = temp / "html"
        output.mkdir()
        env = os.environ.copy()
        tex_paths = [str(ASSET_DIR), f"{site_root}//", f"{source.parent}//"]
        env["TEXINPUTS"] = os.pathsep.join(tex_paths) + os.pathsep + env.get("TEXINPUTS", "")
        subprocess.run(
            [
                "make4ht",
                "-u",
                "-c",
                str(ASSET_DIR / "publication-html.cfg"),
                "-e",
                str(ASSET_DIR / "publication-html.mk4"),
                "-d",
                str(output),
                staged_source.name,
                "mathjax,html5",
            ],
            cwd=temp,
            env=env,
            check=True,
        )
        html_path = output / f"{source.stem}.html"
        return body_fragment(html_path.read_text(encoding="utf-8"), html_path)


def main() -> None:
    args = parse_args()
    source_dir = args.source_dir.resolve()
    output_dir = args.output_dir.resolve()
    site_root = args.site_root.resolve()
    additions = []
    for value in args.metadata_field:
        if "=" not in value:
            raise ValueError(f"Invalid metadata field: {value}")
        key, field_value = value.split("=", 1)
        additions.append(f"{key}: {field_value}")

    output_dir.mkdir(parents=True, exist_ok=True)
    for existing in output_dir.glob("*.html"):
        if GENERATED_MARKER in existing.read_text(encoding="utf-8"):
            existing.unlink()

    sources = sorted(source_dir.glob("*.tex"))
    if not sources:
        raise ValueError(f"No .tex publications found in {source_dir}")

    for source in sources:
        metadata, _ = extract_front_matter(source.read_text(encoding="utf-8"), source)
        fragment = render(source, site_root)
        output = output_dir / f"{source.stem}.html"
        front_matter = "\n".join(["---", *metadata, *additions, "---"])
        output.write_text(
            f"{front_matter}\n{GENERATED_MARKER}\n<div class=\"latex-publication\">\n{fragment}\n</div>\n",
            encoding="utf-8",
        )
        print(f"Rendered {source.relative_to(site_root)} -> {output.relative_to(site_root)}")

    install_shared_assets(args.css_output.resolve())


if __name__ == "__main__":
    main()
